version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0 # TODO. Use nvm
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm test

      - run: curl http://www.google.com/ping?sitemap=https://chatoo2412.github.io/sitemap.xml
